FROM ubuntu:26.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -o Acquire::ForceIPv4=true update && apt-get install -y --no-install-recommends \
    build-essential cmake pkg-config ca-certificates curl git \
    librime-dev librime-bin librime-plugin-lua librime-data \
    libgoogle-glog-dev libmarisa-dev libyaml-cpp-dev libboost-dev libglib2.0-dev darts \
    libboost-filesystem-dev libboost-regex-dev libboost-system-dev \
    ibus-rime fcitx5-rime libfcitx5core-dev fcitx5-modules-dev python3 libpython3.14 python3-venv python3-pip python3-yaml python3-gi python3-pytest \
    gir1.2-gtk-4.0 gir1.2-ibus-1.0 dbus-x11 xvfb xauth \
    fonts-noto-cjk libcangjie3-data lintian && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /work
RUN apt-get -o Acquire::ForceIPv4=true update && \
    apt-get install -y --no-install-recommends x11proto-dev && \
    rm -rf /var/lib/apt/lists/*
