[Addon]
Name=YueKey Dictation
Name[zh_HK]=粵鍵語音輸入
Name[zh_TW]=粵鍵語音輸入
Category=Module
Version=0.4.0
Library=yuekey-dictation
Type=SharedLibrary
OnDemand=False
Configurable=False

[Addon/Dependencies]
0=dbus
