#!/usr/bin/env python3
"""Build reproducible Quick mappings and suffix predictions from open data."""
from collections import defaultdict
import hashlib
import json
from pathlib import Path
import re
import shutil
import sqlite3
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "build/sources"
OUTPUT = ROOT / "build/data"
SAMPLES = {"蘋": "tc", "果": "wd", "公": "ci", "司": "sr", "你": "of", "好": "vd",
           "嘅": "ru", "喺": "rf", "唔": "rr", "冇": "kb", "咗": "rm", "啲": "ri",
           "嚟": "re", "㗎": "rd", "𨋢": "jt"}


def dictionary_rows(path: Path):
    """Codes may include a construction apostrophe; it isn't a keystroke."""
    started = False
    for line in path.read_text().splitlines():
        if line.strip() == "...":
            started = True
            continue
        if started and line and not line.startswith("#"):
            fields = line.split("\t")
            if len(fields) >= 2:
                yield fields


def legacy_punctuation() -> dict[str, list[str]]:
    """Traditional ZXAA–ZXCY follows Big5 A140–A1AC, in three groups of 25.

    Use CP950's Unicode mapping so A145 is ‧ and A14E is ﹑. Do not apply
    compatibility normalization: it would erase the small/vertical forms.
    See docs/PUNCTUATION.md for references and the default candidate table.
    """
    punctuation: dict[str, list[str]] = defaultdict(list)
    for index, trail in enumerate((*range(0x40, 0x7F), *range(0xA1, 0xAD))):
        code = 'z' + chr(ord('a') + index % 25)
        punctuation[code].append(bytes((0xA1, trail)).decode('cp950'))
    return punctuation


def build() -> dict:
    lock = json.loads((ROOT / "data/sources.lock.json").read_text())
    for name, spec in lock["sources"].items():
        if hashlib.sha256((SOURCES / name).read_bytes()).hexdigest() != spec["sha256"]:
            raise ValueError(f"Unverified input: {name}; run make fetch")
    codes: dict[str, set[str]] = defaultdict(set)
    for name in ("cangjie/cangjie5.base.dict.yaml", "quick/quick5.supplement.dict.yaml"):
        for text, full_code, *_ in dictionary_rows(SOURCES / name):
            full_code = full_code.replace("'", "")
            if len(text) == 1 and re.fullmatch("[a-y]+", full_code):
                codes[text].add(full_code if len(full_code) == 1 else full_code[0] + full_code[-1])
    extracted = ROOT / "build/libcangjie"
    extracted.mkdir(parents=True, exist_ok=True)
    subprocess.run(["dpkg-deb", "-x", str(SOURCES / "libcangjie.deb"), str(extracted)], check=True)
    db = extracted / "usr/share/libcangjie/cangjie.db"
    punctuation = legacy_punctuation()
    with sqlite3.connect(f"file:{db}?mode=ro", uri=True) as connection:
        for text, full_code in connection.execute(
            "SELECT chchar, code FROM chars JOIN codes USING(char_index) WHERE version=5 AND hkscs=1"
        ):
            if len(text) == 1 and re.fullmatch("[a-y]+", full_code):
                codes[text].add(full_code if len(full_code) == 1 else full_code[0] + full_code[-1])
    if not punctuation["zb"] or punctuation["zb"][0] != "，":
        raise ValueError("Missing required punctuation mapping: ， zb")

    frequency: dict[str, int] = {}
    for line in (SOURCES / "cantonese/essay-cantonese.txt").read_text().splitlines():
        fields = line.split("\t")
        if len(fields) == 2 and fields[1].isdigit():
            frequency[fields[0]] = int(fields[1])
    for char, code in SAMPLES.items():
        if code not in codes[char]:
            raise ValueError(f"Missing required Hong Kong mapping: {char} {code}")

    OUTPUT.mkdir(parents=True, exist_ok=True)
    shutil.copytree(ROOT / "rime", OUTPUT, dirs_exist_ok=True)
    records = [(code, char, max(frequency.get(char, 0), 1)) for char in codes for code in codes[char]]
    # Keep the original full-code order within each symbol menu. Symbols are
    # deliberately separate from `codes`, which also gates the prediction corpus.
    records.extend((code, char, len(chars) - index)
                   for code, chars in punctuation.items() for index, char in enumerate(chars))
    records.sort(key=lambda row: (row[0], -row[2], row[1]))
    original_notice = (SOURCES / "cangjie/cangjie5.base.dict.yaml").read_text().split("---", 1)[0]
    header = ("# Modified Quick codes and Cantonese weights generated by tools/build_data.py.\n"
              "# See THIRD_PARTY.md for sources, licenses, and changes.\n"
              "# Original base-table notice follows:\n" + original_notice +
              "---\nname: quick_hk\nversion: '0.6.7'\nsort: original\nuse_preset_vocabulary: false\n...\n")
    (OUTPUT / "quick_hk.dict.yaml").write_text(header + "".join(f"{char}\t{code}\t{weight}\n" for code, char, weight in records))

    # The frequency vocabulary also contains common words omitted from the
    # pronunciation files (for example 你好). Include these observed phrases.
    words: set[str] = {text for text in frequency if 2 <= len(text) <= 12 and all(char in codes for char in text)}
    for name in ("cantonese/jyut6ping3.words.dict.yaml", "cantonese/jyut6ping3.phrase.dict.yaml"):
        for text, *_ in dictionary_rows(SOURCES / name):
            if 2 <= len(text) <= 12 and all(char in codes for char in text):
                words.add(text)
    predictions: dict[str, dict[str, int]] = defaultdict(dict)
    for word in sorted(words):
        for split in range(1, min(len(word), 5)):
            prefix, suffix = word[:split], word[split:]
            predictions[prefix][suffix] = max(frequency.get(word, 0), 1)
    # Each prediction is a continuation, never the already committed prefix.
    with (OUTPUT / "quick_hk.predict.tsv").open("w") as output:
        for prefix, choices in sorted(predictions.items()):
            for suffix, weight in sorted(choices.items(), key=lambda row: (-row[1], row[0]))[:90]:
                output.write(f"{prefix}\t{suffix}\t{weight}\n")
    stats = {"characters": len({r[1] for r in records}), "mappings": len(records), "codes": len({r[0] for r in records}),
             "punctuation_mappings": sum(map(len, punctuation.values())),
             "prediction_prefixes": len(predictions), "phrases": len(words), "required_samples": SAMPLES,
             "source_manifest_sha256": hashlib.sha256((ROOT / "data/sources.lock.json").read_bytes()).hexdigest()}
    (OUTPUT / "coverage.json").write_text(json.dumps(stats, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps(stats, ensure_ascii=False))
    return stats


if __name__ == "__main__":
    build()
